### ISSUE TITLE
Mac version?

### ISSUE THREAD

**Issue by Fyb3roptik** [mlabouardy/swaggymnia#1]
I tried to use the linux version on my mac, but to no avail. If you need someone to compile one I can do it!

**Comment by mlabouardy** [comment]
here you go :) 

https://s3.amazonaws.com/swaggymnia/1.0.0-beta/osx/swaggymnia

**Comment by Fyb3roptik** [comment]
Thanks!!!

**Comment by RobertoMSousa** [comment]
Hello @mlabouardy .
I'm trying to run the mac  version but keeps failing me.
I've downloaded.
updated the permissions with `chmod +x swaggymnia`
and then run the comand `./swaggymnia generate -insomnia export.json -config config.json -output json`
But I got this output
```
panic: assignment to entry in nil map

goroutine 1 [running]:
main.parse(0xc420078910, 0x6, 0x3, 0xed1f2d7b0, 0x30e03500, 0x0, 0xc420072a60, 0x1c, 0xc4200cd900, 0x9, ...)
	C:/Users/Mohamed/go/src/github.com/mlabouardy/swaggymnia/swagger.go:51 +0x32c
main.(*Swagger).Generate(0xc4200ef7d8, 0x7ffeefbffc70, 0xb, 0x7ffeefbffc84, 0xb, 0x7ffeefbffc98, 0x4)
	C:/Users/Mohamed/go/src/github.com/mlabouardy/swaggymnia/swagger.go:83 +0x11f
main.main.func1(0xc42008e840, 0x10100, 0xc42008e840)
	C:/Users/Mohamed/go/src/github.com/mlabouardy/swaggymnia/app.go:57 +0x180
github.com/urfave/cli.HandleAction(0x11bd260, 0x12080d8, 0xc42008e840, 0xc42008a300, 0x0)
	C:/Users/Mohamed/go/src/github.com/urfave/cli/app.go:502 +0xd4
github.com/urfave/cli.Command.Run(0x11fab4d, 0x8, 0x0, 0x0, 0xc420078690, 0x1, 0x1, 0x1202246, 0x1e, 0x0, ...)
	C:/Users/Mohamed/go/src/github.com/urfave/cli/command.go:210 +0xb87
github.com/urfave/cli.(*App).Run(0xc4200da1c0, 0xc420076000, 0x8, 0x8, 0x0, 0x0)
	C:/Users/Mohamed/go/src/github.com/urfave/cli/app.go:259 +0x7b7
main.main()
```
