### ISSUE TITLE
swaggymnia.exe on windows not working

### ISSUE THREAD

**Issue by karlos-oliveira** [mlabouardy/swaggymnia#16]
when i try run command **generate**, the **swaggymnia.exe** give me tons of error, most of then related with hardcoded paths.

PS: I downloaded bin file from amazon (as indicated)

Command:

`swaggymnia.exe generate -i 20191024_Requests_Workflow.json -c config.json -o json`

Errors:

```
panic: assignment to entry in nil map

goroutine 1 [running]:
main.parse(0xc04203eaf0, 0x6, 0x4, 0xed54420c0, 0x31698940, 0x0, 0xc042044fa0, 0x1b, 0xc0420e2000, 0x31, ...)
        C:/Users/Mohamed/go/src/github.com/mlabouardy/swaggymnia/swagger.go:51 +0x333
main.(*Swagger).Generate(0xc0420357d8, 0xc042041f50, 0x1f, 0xc04203e1b0, 0xb, 0xc04203e1c5, 0x4)
        C:/Users/Mohamed/go/src/github.com/mlabouardy/swaggymnia/swagger.go:83 +0x126
main.main.func1(0xc042070840, 0x10100, 0xc042070840)
        C:/Users/Mohamed/go/src/github.com/mlabouardy/swaggymnia/app.go:57 +0x187
github.com/urfave/cli.HandleAction(0x5d56a0, 0x622840, 0xc042070840, 0xc04203c300, 0x0)
        C:/Users/Mohamed/go/src/github.com/urfave/cli/app.go:502 +0xdb
github.com/urfave/cli.Command.Run(0x613aa2, 0x8, 0x0, 0x0, 0xc04203e850, 0x1, 0x1, 0x61c792, 0x1e, 0x0, ...)
        C:/Users/Mohamed/go/src/github.com/urfave/cli/command.go:210 +0xb8e
github.com/urfave/cli.(*App).Run(0xc0420b21c0, 0xc042058180, 0x8, 0x8, 0x0, 0x0)
        C:/Users/Mohamed/go/src/github.com/urfave/cli/app.go:259 +0x7be
main.main()
        C:/Users/Mohamed/go/src/github.com/mlabouardy/swaggymnia/app.go:66 +0x51c
```

**Comment by hervehobbes** [comment]
Hello,

Same for me:

```
panic: assignment to entry in nil map

goroutine 1 [running]:
main.parse(0xc04200cb90, 0x6, 0x4, 0xed55c5fe9, 0xf8e8b40, 0x0, 0xc042003620, 0x1b, 0xc0420bc000, 0x1c, ...)
        C:/Users/Mohamed/go/src/github.com/mlabouardy/swaggymnia/swagger.go:51 +0x333
main.(*Swagger).Generate(0xc04202f7d8, 0xc042002ae0, 0xe, 0xc04200c250, 0xb, 0xc04200c225, 0x4)
        C:/Users/Mohamed/go/src/github.com/mlabouardy/swaggymnia/swagger.go:83 +0x126
main.main.func1(0xc04205ab00, 0x10100, 0xc04205ab00)
        C:/Users/Mohamed/go/src/github.com/mlabouardy/swaggymnia/app.go:57 +0x187
github.com/urfave/cli.HandleAction(0x5d56a0, 0x622840, 0xc04205ab00, 0xc042014400, 0x0)
        C:/Users/Mohamed/go/src/github.com/urfave/cli/app.go:502 +0xdb
github.com/urfave/cli.Command.Run(0x613aa2, 0x8, 0x0, 0x0, 0xc04200c8e0, 0x1, 0x1, 0x61c792, 0x1e, 0x0, ...)
        C:/Users/Mohamed/go/src/github.com/urfave/cli/command.go:210 +0xb8e
github.com/urfave/cli.(*App).Run(0xc0420961c0, 0xc042048180, 0x8, 0x8, 0x0, 0x0)
        C:/Users/Mohamed/go/src/github.com/urfave/cli/app.go:259 +0x7be
main.main()
        C:/Users/Mohamed/go/src/github.com/mlabouardy/swaggymnia/app.go:66 +0x51c

```

**Comment by frederikocmr** [comment]
Same for me here!

**Comment by stevesweets** [comment]
I find the same to be true.

**Comment by frederikocmr** [comment]
> I find the same to be true.

This another repository worked for me:
https://github.com/Fyb3roptik/swaggomnia
